### ISSUE TITLE
[1.18.2] Crash when placing Villager from REI into inventory.

### ISSUE THREAD

**Issue by Gbergz** [iamshift/PickableVillagers#1]
**Title^**

**Minecraft:** 1.18.2
**Fabric Version:** 1.18.2-0.14.9
**Fabric API:** 0.58.0-1.18.2
**Mod Version**: pickable_villagers-1.2.0+1.18.2

**Crash-Report:** https://gist.github.com/Gbergz/0c83edd01d36597215bcae01cb2bd396

**Comment by shiftthedev** [comment]
added a fix for the crash
[Pickable Villagers 1.2.2](https://www.curseforge.com/minecraft/mc-mods/pickable-villagers/files/3933866)
