### ISSUE TITLE
1.20 server failing start up

### ISSUE THREAD

**Issue by iStocksy** [iamshift/PickableVillagers#10]
hosting a server on McProHosting and when i add the mod inside the FTP server will not start and unsure why, i added the mod the same way i added my other mods (i'm new to hosting a modded server)

running Fabric and my mods are - BetterF3, Litematica & Malilib - ServerSleep, Wraith Waystones & owo-lib and Xaeros WorldMap and Minimap

**Comment by shiftthedev** [comment]
does it throw an error?

make sure you also add [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files?version=1.20) because it's a requirement.

**Comment by iStocksy** [comment]
i'm dumb lmao, you're a legend brother thank you
