### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pickablevillagers'!

### ISSUE THREAD

**Issue by lol4645** [iamshift/PickableVillagers#11]
version 1.20
[crash-2023-07-02_16.26.01-client.txt](https://github.com/iamshift/PickableVillagers/files/11931636/crash-2023-07-02_16.26.01-client.txt)

**Comment by shiftthedev** [comment]
missing [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files?version=1.20)
