### ISSUE TITLE
Copy trade villager

### ISSUE THREAD

**Issue by D0uze57** [iamshift/PickableVillagers#14]
We can copy a villager profession and trades to an other one while having one in the off hand and the other on the main hand

https://github.com/iamshift/PickableVillagers/assets/77201662/3098c938-6445-4733-811d-365e141db890

**Comment by D0uze57** [comment]
Also placed villager from off hand will loose their profession 

https://github.com/iamshift/PickableVillagers/assets/77201662/4709abd8-db7b-4f20-a0ae-102809388bd0

**Comment by shiftthedev** [comment]
thanks for reporting, I'll have a fix soon.

**Comment by shiftthedev** [comment]
Fixed in latest versions.
If it happen again let me know.
