### ISSUE TITLE
Asks me to "replace mod 'fabric loader' 0.13.11 with version 0.14.12 or later" but I have the latest version of fabric loader.

### ISSUE THREAD

**Issue by MyMst1603** [iamshift/PickableVillagers#15]
![image](https://github.com/iamshift/PickableVillagers/assets/123579278/00ede4cf-fedd-42a7-aa1d-1b2109c921bf)
I tried both versions available on curseforge for 1.19.3 but none worked. I tried updating fabric loader through curseforge, though I don't know how to see and set up a specific version of fabric loader. 
 
this is what I get when I copy error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.11 with version 0.14.12 or later.
Unmet dependency listing:
	 - Mod 'Pickable Villagers' (pickablevillagers) 1.3.5+1.19.3 requires version 0.14.12 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.11!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I do have 42 mods without including the pickable villagers mod but I don't think they're the problem. 

my modpack is vanilla+ with only a single mod adding items.

**Comment by shiftthedev** [comment]
![fabric_loader](https://github.com/iamshift/PickableVillagers/assets/29488158/2b16ea4c-76a0-44dc-ba79-55b65f0273ca)

do this steps to change loader version and let me know if it worked.

**Comment by MyMst1603** [comment]
> ![fabric_loader](https://user-images.githubusercontent.com/29488158/253056057-2b16ea4c-76a0-44dc-ba79-55b65f0273ca.png)
> 
> do this steps to change loader version and let me know if it worked.

works wonderfully. Thank you so much for making life 10x easier!
