### ISSUE TITLE
More an observation than an issue

### ISSUE THREAD

**Issue by Threndon** [iamshift/PickableVillagers#18]
Once I'd realised I needed cloth-config to get the mod to work, I then tried it in 1.20.2-experimental villager trade rebalance, only to realise ... it's experimental! ... so of course, when I created a swamp librarian villager and picked it up and transferred it to a mooshroom biome (it appeared as a swamp librarian villager in my inventory with its description of what trades I'd already done with it), though it remembered its initial trades, and its profession, when I placed it back in the world, it appeared as a plains librarian villager, so when traded to Master, gave the Protection III enchantment, not the Mending one (which I suppose fits with your mod description that it only works with vanilla villagers). Also, they don't seem to recognise the work station (traded with or not) when you pick them up and place them back in the world, until the workstation is broken then replaced. It seems the solution currently is to trade them up to Master before picking them up or moving them to another biome. So, this isn't really an "issue", as the trade rebalance is experimental anyway and subject to change. But, as an observation, whether it may be useful to you in the future remains to be seen, depending on what Mojang do with the trade rebalance! Great mod, by the way!

**Comment by shiftthedev** [comment]
Experimental versions won't be supported because of the their constant changes.
The workstation issue is a known issue that I need to take a closer look again.

**Comment by Threndon** [comment]
Yes, I quite understand! Once I'd realised I was playing in an experimental version, I thought "Duh! Of course!" Thanks for the reply!
