### ISSUE TITLE
Crash on Startup with Fabric for version 1.18.2

### ISSUE THREAD

**Issue by Girzm** [iamshift/PickableVillagers#2]
Minecraft v 1.18.2
Fabric - 0.14.9
fabric-api-0.58.0+1.18.2.jar

**Comment by Girzm** [comment]
[crash-2022-09-02_01.34.59-client.txt](https://github.com/iamshift/PickableVillagers/files/9475115/crash-2022-09-02_01.34.59-client.txt)


i dont know why it uploaded prematurely but here is my log

it is some conflict with Minceraft Comes Alive Reborn

**Comment by shiftthedev** [comment]
fixed in [1.2.3](https://www.curseforge.com/minecraft/mc-mods/pickable-villagers/files/3963856)

**Comment by Girzm** [comment]
thankjs
