### ISSUE TITLE
Villagers not keep their original biome outfits

### ISSUE THREAD

**Issue by shiftthedev** [iamshift/PickableVillagers#20]
Picked and placed the villagers, but they did not keep their original biome outfits.
Pickable Villagers 1.4.4+1.20.1

**Comment by rakantoh** [comment]
yeah, i report and confirm the issue, the pickable villagers not keep their original biome, either babys or adults, MC 1.20.4

**Comment by Ydm2** [comment]
This looks like a comment I once made on Curseforge[yif258], and I'm glad to see it on your to-do list. In the Vanilla game, pressing F3+I can save all the information of a villager in the form of a long command. So I thought maybe you could try making the player press F3+I when trying to pick up a villager, and then save the obtained long command as an item? I am not familiar with Mod related matters, it is just an immature suggestion.

**Comment by shiftthedev** [comment]
this is fixed in dev and will be in the new version.

**Comment by shiftthedev** [comment]
fixed in version 2.0 now available on both [CurseForge](https://www.curseforge.com/minecraft/mc-mods/pickable-villagers) and [Modrinth](https://modrinth.com/mod/pickable-pets)
