### ISSUE TITLE
Crash on Pickup

### ISSUE THREAD

**Issue by Kill-Switch-X** [iamshift/PickableVillagers#21]
On 1.20.1 Fabric 0.14.24 - Using a lot of mods + MCA reborn. Attempt to pickup villager results in a crash (shift  + Rclick), attempted to use the G button but crashed. Subsequent attempts only reveals basic Error Code 1, will provide the first crash log.
[crash-2023-11-20_19.17.51-server.txt](https://github.com/shiftthedev/PickableVillagers/files/13420777/crash-2023-11-20_19.17.51-server.txt)

**Comment by shiftthedev** [comment]
i'll look into it

**Comment by shiftthedev** [comment]
fixed on lastest version
