### ISSUE TITLE
Opening Villagers Not Working - User Error, I'm Sure...

### ISSUE THREAD

**Issue by DumbXBoxAcct** [iamshift/PickableVillagers#23]
Hi - 

My compliments on a great mod!   Looking forward to figuring out how to open villagers with which to trade directly from inventory.  While holding one, right-clicking or shift-right-clicking places the villager and left-clicking uses him as a club.  I definitely have the "Inventory Trade" choice in the config screen set to "Yes" and have tried turning it off and back on again.  Is there some key / click sequence that I'm missing which will let me trade directly with villagers from inventory?  Have also run the mod with as few other mods as possible to avoid conflicts, they are: 

- Fabric 0.15.3 / Minecraft 1.20.1)
- CIT Resewn
- Cloth Config
- Fabric API
- Indium
- JEI
- Sodium
- Pickable Villagers v 1.4.5

[2024-01-15-7.log.gz](https://github.com/shiftthedev/PickableVillagers/files/13945539/2024-01-15-7.log.gz)
[latest.log](https://github.com/shiftthedev/PickableVillagers/files/13945543/latest.log)

**Comment by shiftthedev** [comment]
right-clicking air should open the trade inventory. make sure you're not targeting any block.
i'll be changing this in the future to be more accessible.

**Comment by DumbXBoxAcct** [comment]
Works perfectly.  Thanks, so much, for your quick response!  I'll go ahead and close this out.
