### ISSUE TITLE
Update the mod to 1.20.6?

### ISSUE THREAD

**Issue by CreatorGamer** [iamshift/PickableVillagers#25]
Any chance we could get an update to 1.20.6? I think the mod is great, so I'd love to use it in my updated worlds

**Comment by shiftthedev** [comment]
1.20.6 and 1.21 are planned.
I'm aiming to have it done somewhere mid next month.
It will bring new features and that's why it's taking this long to update.

**Comment by shiftthedev** [comment]
Sorry that took me so long but 1.20.6, 1.21 and 1.21.1 versions are now available on both [CurseForge](https://www.curseforge.com/minecraft/mc-mods/pickable-villagers) and [Modrinth](https://modrinth.com/mod/pickable-pets)
