### ISSUE TITLE
My tps dropping after placing 13 villagers?

### ISSUE THREAD

**Issue by MasterGab1** [iamshift/PickableVillagers#26]
So I was trading with villagers and I moved them to they're chambers, after placing the 13th villagers my tps started dropping like crazy reaching 3 tps when I took a villager back into my pocket my tps became back to normal keep in mind I have lithium installed, This happened on version 1.20.1

**Comment by shiftthedev** [comment]
If you can, see if this still happens with version 2.0 that is now available on both [CurseForge](https://www.curseforge.com/minecraft/mc-mods/pickable-villagers) and [Modrinth](https://modrinth.com/mod/pickable-pets)

**Comment by MasterGab1** [comment]
Yes, it's fixed tysm.
