### ISSUE TITLE
Cannot start server with PickableVillagers on Ubuntu

### ISSUE THREAD

**Issue by ambo** [iamshift/PickableVillagers#27]
Hi, 

first of all thanks you for updating to 1.21.1 and for version 2 of this mod :)

However I am able to start Minecraft on Mac and Windows via Prism Launcher, but I am not able to get it with the same mods on an Ubuntu server. I even tried to start it with only your mod (and the needed ones as well) with the exact same error.

The relevant part seems to be the following

> @Mixin target net.minecraft.class_481$class_483 was not found pickablevillagers.mixins.json:ItemPickerMenuMixin from mod pickablevillagers

More of the Logfile is available here: https://mclo.gs/9vaoKNa

I tried to find a solution but did not succed. Some relevant software versions:

- Java version: 21.0.4.
- Ubuntu: 22.04
- MC: 1.21.1
- fabric loader: 0.16.7

Did you stumble accross something like this before?

Thanks and regards - Andreas

**Comment by shiftthedev** [comment]
What that crash-report tells me is that for some reason the Minecraft version you're using in Linux doesn't have the same classes as Windows does.

Unfortunately this is something I can't test for myself because I don't have a Linux system to do it.
And also, this is the first time someone reports a Linux issue.

**Comment by ambo** [comment]
Thanks for your reply. I was pretty sure its something exotic, but just to be sure: previous versions of your mod worked fine on the same environment with 1.20, did you use the same classes in the older versions? I am pretty sure that the MC java versions should be consistent across plattforms and its the first time that I have such an issue. I prepare server mods on local mac or windows machines to put them onto linux servers for years now.

But maybe this issue can stay open just in case somebody searches for this particular error message? And if someone reads this who solved this issue on the client (or server) side, it would be awesome to post possible solutions here.

Thanks!

**Comment by shiftthedev** [comment]
In the latest version (2.0.2) I've made some changes to how server-client network works.
I would appreciate if you could try it and let me know if it works on Linux now.

**Comment by ambo** [comment]
Thanks for your work on that issue. I can confirm that it is fixed with version 2.0.2 in my environment. Nice!
