### ISSUE TITLE
[Fabric 1.19.2] - Unlocked villagers wont link to work station.

### ISSUE THREAD

**Issue by DemonSlayer112** [iamshift/PickableVillagers#3]
Hello.
If you pick a villager you never traded with, and place it back down they seem to refuse to get a new job, or link to a valid composter.
This not only makes it pointless to move villagers but will also disallow them from restocking if they don't link to the correct station to do so.

**Comment by shiftthedev** [comment]
I'm unable to replicate this problem.
I'll be needing a log to check for errors an possible compatibility issues.

**Comment by DemonSlayer112** [comment]
Um, I was unable to recreate this with a creative mode villager from egg.
But I then made a super flat world and located a village.
I grabbed the first villager I saw that had a job(a fletcher) and flew away. This villager seemingly had the same issue. Wouldn't give up job, nor link to new station.

Perhaps the issue is with naturally spawned villagers?
I have the world ready if you wanna examine it, its a custom modpack so let me know if I should just send the whole file.
Anyways, here the modlist, I figured it was a Overhauled village issue, but the village in the superflat was vanilla:
![image](https://user-images.githubusercontent.com/70122500/198932544-abc0fd25-4e59-461a-b6f2-da6063897ca9.png)

Not sending the log as I looked at it, there was no entry of me picking the fletcher nor any data about it's interaction, so I figured I might as well not send it.

**Comment by DemonSlayer112** [comment]
Quick Update:
I tested in a simpler modpack with just the mod and its dependencies and the issue still persists.
Log of this(doesn't seem to say much): 
[latest.log](https://github.com/iamshift/PickableVillagers/files/9898151/latest.log)

**Comment by shiftthedev** [comment]
released a possible fix - https://www.curseforge.com/minecraft/mc-mods/pickable-villagers/files/4060267
if possible let me know if it work fine or not.

**Comment by Kyzoku** [comment]
I don't know if this is the same issue, but I picked up a villager that I hadn't traded with who has a job and placed them right back down where they were standing (next to their station) and it now had no job and refused take a job again.

This happened on Minecraft 1.18, Pickable Villagers 1.2.4.

**Comment by shiftthedev** [comment]
> I don't know if this is the same issue, but I picked up a villager that I hadn't traded with who has a job and placed them right back down where they were standing (next to their station) and it now had no job and refused take a job again.
> 
> This happened on Minecraft 1.18, Pickable Villagers 1.2.4.

i tried to replicate that but was unable to.
if possible share a log after this happened.

**Comment by Kyzoku** [comment]
> > I don't know if this is the same issue, but I picked up a villager that I hadn't traded with who has a job and placed them right back down where they were standing (next to their station) and it now had no job and refused take a job again.
> > This happened on Minecraft 1.18, Pickable Villagers 1.2.4.
> 
> i tried to replicate that but was unable to. if possible share a log after this happened.

Absolutely nothing is shown in the log.  I captured a short video in case you were interested.
https://anonfiles.com/q6T6s2F1y4/PickableVillagers_Issue_mp4

**Comment by DemonSlayer112** [comment]
> released a possible fix - https://www.curseforge.com/minecraft/mc-mods/pickable-villagers/files/4060267 if possible let me know if it work fine or not.

It works! :D
And it seems to fix villagers previously in this situation!
It doesn't keep the trade the villager had before hand if directly placed in front of the workstation but that's 100% up to someone who doesn't lock them first!
Ty for the fix :)

Also for Kyzoku's issue, this is the same one which seems to be fixed with your fix.

**Comment by shiftthedev** [comment]
> > > I don't know if this is the same issue, but I picked up a villager that I hadn't traded with who has a job and placed them right back down where they were standing (next to their station) and it now had no job and refused take a job again.
> > > This happened on Minecraft 1.18, Pickable Villagers 1.2.4.
> > 
> > 
> > i tried to replicate that but was unable to. if possible share a log after this happened.
> 
> Absolutely nothing is shown in the log. I captured a short video in case you were interested. https://anonfiles.com/q6T6s2F1y4/PickableVillagers_Issue_mp4

breaking and placing the station should fix it.
