### ISSUE TITLE
Mod crashes when opening the game . 

### ISSUE THREAD

**Issue by Aboniewya** [iamshift/PickableVillagers#31]
The mod was working a couple of hours ago but then when I opened the game it wouldn't let me load in 

[crash-2024-11-19_17.51.52-client.txt](https://github.com/user-attachments/files/17839871/crash-2024-11-19_17.51.52-client.txt)
 
im not sure if that link works as this is my first time with an issue with this .

**Comment by shiftthedev** [comment]
have you disabled the Trader in the config?

**Comment by Aboniewya** [comment]
I think i did .

**Comment by shiftthedev** [comment]
its a known bug that will be fixed in the next update. 
for now you need to leave it enabled.

**Comment by Aboniewya** [comment]
aii ty I'll look forward to the update .
