### ISSUE TITLE
Can't install the Pickable Villagers mod.

### ISSUE THREAD

**Issue by Grofilo51** [iamshift/PickableVillagers#4]
[crash-2022-12-26_09.43.03-client.txt](https://github.com/iamshift/PickableVillagers/files/10302617/crash-2022-12-26_09.43.03-client.txt)

**Comment by shiftthedev** [comment]
you're missing [Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3972420)

**Comment by Grofilo51** [comment]
Thanks! Didn't know it's that easy.
