### ISSUE TITLE
I cant load up minecraft,

### ISSUE THREAD

**Issue by GooseOnCrack** [iamshift/PickableVillagers#5]
![image](https://user-images.githubusercontent.com/122092545/210998633-096e9f3f-f2cc-443e-988c-092db10742bb.png)
![image](https://user-images.githubusercontent.com/122092545/210998670-07c67f76-9608-4ccb-8158-6fdfad538427.png)
these are the issues, please respond asap! :D
![image_2023-01-06_215608993](https://user-images.githubusercontent.com/122092545/210998726-1bfadee3-b840-4db7-960f-6851a69984fd.png)

**Comment by shiftthedev** [comment]
you're missing [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
