### ISSUE TITLE
Can't disable pickup cost

### ISSUE THREAD

**Issue by Freshlancer** [iamshift/PickableVillagers#6]
When playing with the mod, I can set the slider to 0 in the settings, but returning to gameplay, no change has happened. Picking up villagers still costs levels.

**Comment by shiftthedev** [comment]
minecraft version? mod version?

**Comment by Freshlancer** [comment]
Java 1.19.2, and I'm using v1.3.4+1.19.2

Sorry, forgot to include those

**Comment by shiftthedev** [comment]
i'll look into it.

**Comment by shiftthedev** [comment]
I was unable to replicate it. 
can you provide a latest.log after the problem occurred?

**Comment by Freshlancer** [comment]
[latest.log](https://github.com/iamshift/PickableVillagers/files/10530622/latest.log)

**Comment by Freshlancer** [comment]
For the sake of thoroughly describing my setup as well, I'm playing on a locally hosted server (hosted on my PC) with the mod installed both client side and server side. The other villager-related mod installed is the trade cycling mod. Thanks again!

**Comment by shiftthedev** [comment]
there is nothing wrong with the mod. the problem is that ModMenu only changes client configs and because your playing on a server you need to manually change the server config.
