### ISSUE TITLE
1.20 Server ERROR

### ISSUE THREAD

**Issue by mss0517** [iamshift/PickableVillagers#9]
My server Minecraft version is 1.20, and I downloaded the corresponding version pickable_villagers-1.4.0+1.20.jar in curseforge, and he reported the following error that requires version 1.20.1:
[main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Pickable Villagers' (pickablevillagers) 1.4.0+1.20 with any version that is compatible with:
                 - minecraft 1.20
Unmet dependency listing:
         - Mod 'Pickable Villagers' (pickablevillagers) 1.4.0+1.20 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!

**Comment by shiftthedev** [comment]
should be fixed in 1.4.1
